eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
okta:
  oauth2:
    issuer: https://dev-324234.okta.com/oauth2/default
    audience: api://default
